import { ArrowUpRight } from "lucide-react"
import { Badge } from "@/components/ui/badge"

export const GallerySection = () => (
  <section className="mx-auto max-w-7xl px-6 py-20 text-center">
    <h2 className="mb-2 font-bold text-3xl text-white">
      Neural Canvas Gallery
    </h2>
    <p className="mb-12 text-slate-400">
      Explore components generated by our community using the latest Aether v4.0
      model.
    </p>

    <div className="grid grid-cols-1 gap-6 text-left lg:grid-cols-12">
      {/* Large Left Card */}
      <div className="group relative overflow-hidden rounded-2xl border border-slate-800 bg-slate-900 lg:col-span-8">
        <div className="absolute inset-0 z-10 bg-gradient-to-b from-transparent to-slate-950/90"></div>
        {/* Mock Image Placeholder - Replace with actual Image component */}
        <div className="flex h-[400px] w-full items-center justify-center border-slate-800 border-b bg-[#111827] p-8">
          <div className="flex h-full w-full items-end rounded-xl border border-slate-700/50 bg-slate-800/30 p-4">
            {/* Abstract chart representation */}
            <svg
              viewBox="0 0 100 40"
              className="h-32 w-full fill-cyan-500/10 stroke-cyan-500 drop-shadow-[0_0_10px_rgba(34,211,238,0.3)]"
            >
              <path d="M0 40 Q 10 20 20 25 T 40 10 T 60 30 T 80 15 T 100 5 L 100 40 Z" />
            </svg>
          </div>
        </div>
        <div className="absolute bottom-0 left-0 z-20 flex w-full items-end justify-between p-6">
          <div>
            <Badge variant="default" className="mb-3 px-2 py-0.5 text-[10px]">
              DASHBOARD
            </Badge>
            <h3 className="font-bold text-white text-xl">Quant Edge Pro</h3>
          </div>
          <button className="flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-white backdrop-blur transition hover:bg-white/20">
            <ArrowUpRight size={18} />
          </button>
        </div>
      </div>

      {/* Right Small Cards */}
      <div className="flex flex-col gap-6 lg:col-span-4">
        <div className="relative flex-1 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900">
          <div className="absolute inset-0 z-10 bg-gradient-to-t from-slate-950/90 to-transparent"></div>
          <div className="flex h-full min-h-[190px] w-full items-center justify-center bg-[#111827] p-4">
            {/* Mock Mobile UI */}
            <div className="h-40 w-32 rounded-xl border border-slate-700 bg-slate-800/50"></div>
          </div>
          <div className="absolute bottom-0 left-0 z-20 p-5">
            <Badge variant="secondary" className="mb-2 text-[10px]">
              MOBILE
            </Badge>
            <h3 className="font-bold text-lg text-white">Voyage OS</h3>
          </div>
        </div>
        <div className="relative flex-1 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900">
          <div className="absolute inset-0 z-10 bg-gradient-to-t from-slate-950/90 to-transparent"></div>
          <div className="flex h-full min-h-[190px] w-full items-center justify-center bg-[#111827] p-4">
            {/* Mock Robot/Commerce UI */}
            <div className="h-32 w-40 rounded-xl border border-slate-700 bg-slate-800/50"></div>
          </div>
          <div className="absolute bottom-0 left-0 z-20 p-5">
            <Badge className="mb-2 border border-yellow-500/30 bg-yellow-500/20 text-[10px] text-yellow-500">
              COMMERCE
            </Badge>
            <h3 className="font-bold text-lg text-white">Apex Hardware</h3>
          </div>
        </div>
      </div>
    </div>
  </section>
)
