import { Badge } from "@/components/ui/badge";
import { ArrowUpRight } from "lucide-react";

export const GallerySection = () => (
    <section className="py-20 px-6 max-w-7xl mx-auto text-center">
        <h2 className="text-3xl font-bold text-white mb-2">Neural Canvas Gallery</h2>
        <p className="text-slate-400 mb-12">Explore components generated by our community using the latest Aether v4.0 model.</p>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 text-left">
            {/* Large Left Card */}
            <div className="lg:col-span-8 rounded-2xl bg-slate-900 border border-slate-800 overflow-hidden relative group">
                <div className="absolute inset-0 bg-gradient-to-b from-transparent to-slate-950/90 z-10"></div>
                {/* Mock Image Placeholder - Replace with actual Image component */}
                <div className="h-[400px] w-full bg-[#111827] flex items-center justify-center border-b border-slate-800 p-8">
                    <div className="w-full h-full border border-slate-700/50 rounded-xl bg-slate-800/30 flex items-end p-4">
                        {/* Abstract chart representation */}
                        <svg viewBox="0 0 100 40" className="w-full h-32 stroke-cyan-500 fill-cyan-500/10 drop-shadow-[0_0_10px_rgba(34,211,238,0.3)]">
                            <path d="M0 40 Q 10 20 20 25 T 40 10 T 60 30 T 80 15 T 100 5 L 100 40 Z" />
                        </svg>
                    </div>
                </div>
                <div className="absolute bottom-0 left-0 w-full p-6 z-20 flex justify-between items-end">
                    <div>
                        <Badge variant="default" className="mb-3 text-[10px] px-2 py-0.5">DASHBOARD</Badge>
                        <h3 className="text-xl font-bold text-white">Quant Edge Pro</h3>
                    </div>
                    <button className="w-10 h-10 rounded-full bg-white/10 backdrop-blur flex items-center justify-center text-white hover:bg-white/20 transition">
                        <ArrowUpRight size={18} />
                    </button>
                </div>
            </div>

            {/* Right Small Cards */}
            <div className="lg:col-span-4 flex flex-col gap-6">
                <div className="flex-1 rounded-2xl bg-slate-900 border border-slate-800 overflow-hidden relative">
                    <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 to-transparent z-10"></div>
                    <div className="h-full w-full bg-[#111827] min-h-[190px] p-4 flex items-center justify-center">
                        {/* Mock Mobile UI */}
                        <div className="w-32 h-40 border border-slate-700 rounded-xl bg-slate-800/50"></div>
                    </div>
                    <div className="absolute bottom-0 left-0 p-5 z-20">
                        <Badge variant="secondary" className="mb-2 text-[10px]">MOBILE</Badge>
                        <h3 className="text-lg font-bold text-white">Voyage OS</h3>
                    </div>
                </div>
                <div className="flex-1 rounded-2xl bg-slate-900 border border-slate-800 overflow-hidden relative">
                    <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 to-transparent z-10"></div>
                    <div className="h-full w-full bg-[#111827] min-h-[190px] p-4 flex items-center justify-center">
                        {/* Mock Robot/Commerce UI */}
                        <div className="w-40 h-32 border border-slate-700 rounded-xl bg-slate-800/50"></div>
                    </div>
                    <div className="absolute bottom-0 left-0 p-5 z-20">
                        <Badge className="bg-yellow-500/20 text-yellow-500 border border-yellow-500/30 mb-2 text-[10px]">COMMERCE</Badge>
                        <h3 className="text-lg font-bold text-white">Apex Hardware</h3>
                    </div>
                </div>
            </div>
        </div>
    </section>
);