import { ArrowUpRight } from "lucide-react"
import { Badge } from "~/shared/components/ui/badge"

export const GallerySection = () => (
  <section className="mx-auto max-w-7xl px-6 py-20 text-center">
    <h2 className="mb-2 font-bold text-3xl text-foreground">
      Neural Canvas Gallery
    </h2>
    <p className="mb-12 text-muted-foreground">
      Explore components generated by our community using the latest Sappy
      model.
    </p>

    <div className="grid grid-cols-1 gap-6 text-left lg:grid-cols-12">
      {/* Large Left Card */}
      <div className="group relative overflow-hidden rounded-2xl border border-border bg-card lg:col-span-8">
        <div className="absolute inset-0 z-10 bg-linear-to-b from-transparent to-background/90" />
        <div className="flex h-100 w-full items-center justify-center border-border border-b bg-muted/40 p-8">
          <div className="flex h-full w-full items-end rounded-xl border border-border/60 bg-background/40 p-4">
            <svg
              aria-hidden="true"
              viewBox="0 0 100 40"
              className="h-32 w-full fill-primary/10 stroke-primary drop-shadow-[0_0_10px_var(--primary)]"
            >
              <path d="M0 40 Q 10 20 20 25 T 40 10 T 60 30 T 80 15 T 100 5 L 100 40 Z" />
            </svg>
          </div>
        </div>
        <div className="absolute bottom-0 left-0 z-20 flex w-full items-end justify-between p-6">
          <div>
            <Badge className="mb-3">DASHBOARD</Badge>
            <h3 className="font-bold text-foreground text-xl">
              Quant Edge Pro
            </h3>
          </div>
          <button
            type="button"
            aria-label="Open Quant Edge Pro"
            className="flex size-10 items-center justify-center rounded-full bg-foreground/10 text-foreground backdrop-blur transition hover:bg-foreground/20"
          >
            <ArrowUpRight size={18} />
          </button>
        </div>
      </div>

      {/* Right Small Cards */}
      <div className="flex flex-col gap-6 lg:col-span-4">
        <div className="relative flex-1 overflow-hidden rounded-2xl border border-border bg-card">
          <div className="absolute inset-0 z-10 bg-linear-to-t from-background/90 to-transparent" />
          <div className="flex h-full min-h-47.5 w-full items-center justify-center bg-muted/40 p-4">
            <div className="h-40 w-32 rounded-xl border border-border bg-background/50" />
          </div>
          <div className="absolute bottom-0 left-0 z-20 p-5">
            <Badge variant="secondary" className="mb-2">
              MOBILE
            </Badge>
            <h3 className="font-bold text-foreground text-lg">Voyage OS</h3>
          </div>
        </div>
        <div className="relative flex-1 overflow-hidden rounded-2xl border border-border bg-card">
          <div className="absolute inset-0 z-10 bg-linear-to-t from-background/90 to-transparent" />
          <div className="flex h-full min-h-47.5 w-full items-center justify-center bg-muted/40 p-4">
            <div className="h-32 w-40 rounded-xl border border-border bg-background/50" />
          </div>
          <div className="absolute bottom-0 left-0 z-20 p-5">
            <Badge variant="outline" className="mb-2">
              COMMERCE
            </Badge>
            <h3 className="font-bold text-foreground text-lg">Apex Hardware</h3>
          </div>
        </div>
      </div>
    </div>
  </section>
)
